# Generated by Django 5.1.3 on 2024-11-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_pessoa_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('autor_email', models.EmailField(max_length=254)),
                ('publicado', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
